apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "energy-pipeline.fullname" . }}-processing-service
  labels:
    {{- include "energy-pipeline.processingService.labels" . | nindent 4 }}
    assignment-id: {{ .Values.assignmentId | quote }}
spec:
  replicas: {{ .Values.processingService.replicaCount }}
  selector:
    matchLabels:
      {{- include "energy-pipeline.processingService.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "energy-pipeline.processingService.labels" . | nindent 8 }}
        assignment-id: {{ .Values.assignmentId | quote }}
    spec:
      containers:
        - name: processing-service
          image: "{{ .Values.processingService.image.repository }}:{{ .Values.processingService.image.tag }}"
          imagePullPolicy: {{ .Values.processingService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.processingService.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "energy-pipeline.fullname" . }}-config
          env:
            - name: CONSUMER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.processingService.resources | nindent 12 }}
