apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "energy-pipeline.fullname" . }}-ingestion-api
  labels:
    {{- include "energy-pipeline.ingestionApi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ingestionApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "energy-pipeline.ingestionApi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "energy-pipeline.ingestionApi.labels" . | nindent 8 }}
    spec:
      containers:
        - name: ingestion-api
          image: "{{ .Values.ingestionApi.image.repository }}:{{ .Values.ingestionApi.image.tag }}"
          imagePullPolicy: {{ .Values.ingestionApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ingestionApi.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "energy-pipeline.fullname" . }}-config
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.ingestionApi.resources | nindent 12 }}
