apiVersion: v1
kind: Service
metadata:
  name: {{ include "energy-pipeline.fullname" . }}-ingestion-api
  labels:
    {{- include "energy-pipeline.ingestionApi.labels" . | nindent 4 }}
    assignment-id: {{ .Values.assignmentId | quote }}
spec:
  type: {{ .Values.ingestionApi.service.type }}
  ports:
    - port: {{ .Values.ingestionApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "energy-pipeline.ingestionApi.selectorLabels" . | nindent 4 }}
